# Generated by Django 3.0.6 on 2020-05-21 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 21, 12, 46, 5, 812178, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
