# Generated by Django 3.0.6 on 2020-05-22 04:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_editor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default=datetime.datetime(2020, 5, 22, 4, 38, 44, 225290, tzinfo=utc), upload_to='articles/'),
            preserve_default=False,
        ),
    ]
